### GET TASKS
GET http://localhost:3003/story-associations

### POST TASK
POST http://localhost:3003/story-associations
Content-Type: application/json

{
  "id_usuario": 1,
  "nombre_diccionario": "erick@notion.com",
  "descripcion": "Diccionario de Erick"
}

### GET TASK BY ID
GET http://localhost:3003/story-associations/1

### Get Association with word
GET http://localhost:3003/story-associations/word/alien

### GET Association with Content
GET http://localhost:3003/story-associations/1/content

### PUT TASK
PUT http://localhost:3003/story-associations/1
Content-Type: application/json

{
  "descripcion": "Diccionario de las mil noches"
}

### DELETE TASK
DELETE http://localhost:3003/story-associations/2


