### GET TASKS
GET http://localhost:3003/users

### POST TASK
POST http://localhost:3003/users
Content-Type: application/json

{
  "nombre_usuario": "erickloolpez",
  "email": "erick@notion.com"
}

### GET TASK BY ID
GET http://localhost:3003/users/1

### PUT TASK
PUT http://localhost:3003/users/1
Content-Type: application/json

{
  "email": "erick@gmail.com"
}

### DELETE TASK
DELETE http://localhost:3003/users/2


