
### GET TASKS
GET http://localhost:3003/associations

### POST TASK
POST http://localhost:3003/associations
Content-Type: application/json

{
  "id_diccionario": 1,
  "palabra": "diantres",
  "relacion": "repudio"
}

### GET TASK BY ID
GET http://localhost:3003/associations/1

### GET Association with word
GET http://localhost:3003/associations/word/abuela

### PUT TASK
PUT http://localhost:3003/associations/5
Content-Type: application/json

{
  "word": "azucar"
}

### DELETE TASK
DELETE http://localhost:3003/associations/2


